apiVersion: apps/v1
kind: Deployment
metadata:
  name: site1
spec:
  selector:
    matchLabels:
      app: site1
  replicas: 2
  template:
    metadata:
      labels:
        app: site1
    spec:
      containers:
      - name: site1
        image: site1:1.0.0
        ports:
        - containerPort: 80
